---
sudo: false
language: ruby
rvm:
  - "2.1.0"
  - "2.0.0"
script:
  - bundle exec rspec spec
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 4.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
